---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
  labels:
    app: openmrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      containers:
        - image: openmrs/openmrs-reference-application-distro:2.6
          name: openmrs
          ports:
            - containerPort: 8080        