---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ap-azure-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
spec:
  containers:
    - name: mysqldb
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: apecommerce
        - name: MYSQL_USER
          value: apdevops
        - name: MYSQL_PASSWORD
          value: Learning@2022
      volumeMounts:
        - name: dbvol
          mountPath: /var/lib/mysql
  volumes:
    - name: dbvol
      persistentVolumeClaim:
        claimName: ap-azure-managed-disk